name: quality lints

on:
  push:
  pull_request:
  schedule:
    - cron: "0 18 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          persist-credentials: false

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt

      - name: clippy
        run: cargo +stable clippy --all-features --all-targets -- --deny warnings

      - name: rustfmt
        run: cargo +stable fmt --check
